name: Build Checks
on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress tests run
        uses: cypress-io/github-action@v4
